# Generated by Django 2.2.1 on 2019-05-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('year', models.CharField(max_length=5)),
                ('rated', models.CharField(max_length=5)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=8)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=200)),
                ('metascore', models.CharField(max_length=10)),
                ('imdbRating', models.CharField(max_length=10)),
                ('imdbVotes', models.CharField(max_length=15)),
                ('imdbID', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=20)),
                ('DVD', models.CharField(max_length=20)),
                ('boxOffice', models.CharField(max_length=30)),
                ('production', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('response', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('date', models.DateField(default='2019-05-17')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
